[package]
name = "open_shmup_import"
version = "0.0.0"
edition = "2021"

[dependencies]
byteorder = "=1.5.0"
clap = { version = "=4.5.40", features = ["derive"] }
open_shmup_data = { path = "../data" }